### ISSUE TITLE
Application ends before all logs are printed to console using async execution method

### ISSUE THREAD

**Issue by rahul0x24** [Nike-Inc/Willow#47]
I am using Willow in a Swift CLI application and facing an issue where my program terminates before all my logs are printed to the console.

![Supporting Image](https://i.imgur.com/unWYBFN.png)

**Comment by cnoon** [comment]
Hi @RahulKatariya,

Thank you for submitting this issue. We haven't used Willow internally for any CLI tools (AFAIK), so your use case is the first time we've considered it. Since you've taken the time to also submit a PR in #48, I'm going to go ahead and close this issue out and we'll continue the discussion there.

Thanks! 🍻
